### ISSUE TITLE
Show more than 8 participatory process in home page

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-trianon#3]
Our client want's to show 12 participatory process on the home page. 
<img width="420" alt="capture d ecran 2018-02-05 a 19 22 21" src="https://user-images.githubusercontent.com/11473995/35821649-01c872ca-0aaa-11e8-8362-730243153cdd.png">
@juliesimon found a fix for this. She will send a PR.

**Comment by juliesimon** [comment]
@ludivinecp I first wanted to do a PR on `f-moderation` on the `decidim` repo but 1/the branch is locked 2/I was about to commit a whole bunch of stuff so you just might want to change it yourself when you'll be working on the code of trianon :
`OpenSourcePolitics/decidim/decidim-participatory_processes/app/queries/decidim/participatory_processes/highlighted_participatory_processes.rb`

```
module Decidim
  module ParticipatoryProcesses
    # This query selects some prioritized processes.
    class HighlightedParticipatoryProcesses < Rectify::Query
      def query
        PrioritizedParticipatoryProcesses.new.query.limit(12)
      end
    end
  end
end
```

<img width="1440" alt="capture d ecran 2018-02-06 a 09 51 37" src="https://user-images.githubusercontent.com/29771726/35850488-5578ba80-0b25-11e8-826f-2da0c3442faf.png">
